@baseUrl = http://localhost:3000/api
# Categories

@resourceName = products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?price_gte=900

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?name_like=tasty

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=20

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc


###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "f1c585ef-742d-478a-83fd-96095e5414a8",
    "name": "Awesome Steel Ball",
    "color": "white",
    "price": 960,
    "description": "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    "thumbnailUrl": "http://placeimg.com/400/400"
}

### 

# @name updateNew
PATCH {{baseUrl}}/{{resourceName}}/NvShf1g
Content-Type: application/json

{
    "name": "Awesome Steel Ball Update",
    "color": "red",
    "price": 950
}

###

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/3


